[warning]
showWarningOnDirectExecution=true

[logger]
level="debug"

[runner]
magicEnabled=true

[serve]
folderWatchBlacklist=['']

headless=false

runonsave=false

port=8051

enableCORS=false

[browser]
serverAddress="localhost"

gatherUsageStats=true

serverport=8051